import assert from "node:assert/strict";
import { test } from "node:test";

import { testProject } from "./fixtures";
import { graphHash, isStaleGraph } from "./graph";

test("this hash agrees with the compiler's canonical test vector", () => {
  assert.equal(
    graphHash({
      package: "demo.flow",
      workflow: {
        subroutine: "main", profiles: [], sessions: [],
        profile_arguments: {}, session_arguments: {},
      },
      subroutine: {
        id: "main",
        name: "München",
        ports: { enter: "enter", exit: "exit", failure: "failure" },
        features: [],
        profile_parameters: [],
        profiles: [],
        session_parameters: [],
        sessions: [],
        nodes: [
          { id: "enter", name: "enter", kind: "enter", operation: {} },
          { id: "exit", name: "exit", kind: "exit", operation: {} },
          { id: "failure", name: "failure", kind: "failure", operation: {} },
        ],
        edges: [
          {
            id: "enter__exit",
            name: "then",
            source: "enter",
            target: "exit",
            conditions: [],
            effects: [],
          },
        ],
        workflows: [],
        subroutines: [],
      },
      externals: [],
      sources: [
        { ownership: "user", path: "src/β.py", sha256: "a".repeat(64) },
        { ownership: "user", path: "src/\u{10000}.py", sha256: "b".repeat(64) },
        { ownership: "user", path: "src/\uE000.py", sha256: "c".repeat(64) },
      ],
    }),
    "91723b6bbe2ffb699d6514b964bb1380b449f620b4ba009cd497871403ec42f8",
  );
});

test("an edit to the graph moves the hash, and a move of a node does not", () => {
  const project = testProject();
  const before = graphHash(project);

  const moved = structuredClone(project);
  moved.editor = { layouts: { main: { enter: { x: 400, y: -30 } } } };
  assert.equal(graphHash(moved), before, "layout must never change a generated byte");

  const edited = structuredClone(project);
  (edited.workflow as Record<string, unknown>).subroutine = "other";
  assert.notEqual(graphHash(edited), before);
  edited.generated_from = before;
  assert.equal(isStaleGraph(edited), true);

  const retyped = structuredClone(project);
  const owned = (retyped.sources as Record<string, unknown>[]).find(
    (entry) => entry.ownership === "user",
  )!;
  owned.sha256 = "f".repeat(64);
  assert.notEqual(graphHash(retyped), before);

  const regenerated = structuredClone(project);
  const produced = (regenerated.sources as Record<string, unknown>[]).find(
    (entry) => entry.ownership === "generated",
  )!;
  produced.sha256 = "e".repeat(64);
  assert.equal(graphHash(regenerated), before);
});

test("key order in the file does not change the hash", () => {
  const project = testProject();
  const reordered = Object.fromEntries(Object.entries(project).reverse());
  assert.equal(graphHash(reordered), graphHash(project));
});

test("ID-keyed collection order matches the native maps", () => {
  const project = testProject();
  const root = project.subroutine as Record<string, unknown>;
  const child = structuredClone((root.subroutines as Record<string, unknown>[])[0]);
  child.id = "audit";
  child.name = "Audit";
  (root.subroutines as Record<string, unknown>[]).push(child);
  root.workflows = [
    { external: { alias: "pin.z", workflow: "main" }, id: "z_remote", name: "Z" },
    { external: { alias: "pin.a", workflow: "main" }, id: "a_remote", name: "A" },
  ];
  project.externals = [
    {
      alias: "pin.z", commit: "a".repeat(40), name: "z", owner: "example",
      package: "example.z", provider: "github", repository_id: 2,
    },
    {
      alias: "pin.a", commit: "b".repeat(40), name: "a", owner: "example",
      package: "example.a", provider: "github", repository_id: 1,
    },
  ];

  const reordered = structuredClone(project);
  (reordered.externals as unknown[]).reverse();
  const reverse = (raw: Record<string, unknown>): void => {
    for (const key of ["nodes", "edges", "workflows", "subroutines"] as const) {
      (raw[key] as unknown[]).reverse();
    }
    for (const nested of raw.subroutines as Record<string, unknown>[]) reverse(nested);
  };
  reverse(reordered.subroutine as Record<string, unknown>);
  assert.equal(graphHash(reordered), graphHash(project));
});

test("ordered semantic collections remain ordered", () => {
  const project = testProject();
  const root = project.subroutine as Record<string, unknown>;
  (root.features as Record<string, unknown>[]).push({
    description: "A second counter.", id: "other", kind: "integer", label: "Other",
  });
  const edge = (root.edges as Record<string, unknown>[])[1];
  edge.conditions = [
    { feature_id: "remaining_iterations", observation: "greater_zero" },
    { feature_id: "other", observation: "equal_zero" },
  ];
  edge.effects = [
    { feature_id: "remaining_iterations", observation: "decreases" },
    { feature_id: "other", observation: "increases" },
  ];

  for (const [owner, key] of [
    [root, "features"],
    [edge, "conditions"],
    [edge, "effects"],
  ] as const) {
    const reordered = structuredClone(project);
    const clonedRoot = reordered.subroutine as Record<string, unknown>;
    const clonedEdge = (clonedRoot.edges as Record<string, unknown>[])[1];
    const clonedOwner = owner === root
      ? clonedRoot
      : owner === edge
        ? clonedEdge
        : reordered.workflow as Record<string, unknown>;
    (clonedOwner[key] as unknown[]).reverse();
    assert.notEqual(graphHash(reordered), graphHash(project), key);
  }
});
